# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  "https://github.com/#{repo_name}"
end

gem 'colorize'
gem 'rspec'
gem 'rspec-core'
gem 'rubocop'
gem 'rubocop-rspec', require: false
