name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  regression:
    name: Regression
    runs-on: ubuntu-latest
    env:
      working-directory: tests
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Build
        run: go get -v -t -d ./...
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
      - name: Install Dependencies
        run: make setup-tests
      - name: Run Tests
        run: make test-regression
      - name: Lint
        working-directory: ${{env.working-directory}}
        run: bundle exec rubocop

  golang:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Test
        run: make test-go
      - name: Lint
        run: |
          # install [[https://github.com/alecthomas/gometalinter][gometalinter]] first.
          curl -L https://git.io/vp6lP | sh
          PATH="$PATH:./bin/"
          go get github.com/gojp/goreportcard/cmd/goreportcard-cli
          goreportcard-cli -v -t 85
